print("PERSONAL INFORMATION DISPLAY PROGRAM")
print("=" * 40)
name = input("Name: ")
age = input("Age: ")
gender = input("Gender: ")
address = input("Address: ")
email = input("Email: ")
contact = input("Contact Number: ")
print()
print("----- PERSONAL INFORMATION -----")
print(f"Name: {name}")
print(f"Age: {age}")
print(f"Gender: {gender}")
print(f"Address: {address}")
print(f"Email: {email}")
print(f"Contact Number: {contact}")
print("--------------------------------")
print("Thank you for providing your details.")
print("Please review your information above.")
print("If there are errors, restart the program.")
print("This program is for educational use.")
print("Developed using Python.")
print("Have a great day!")
print("=" * 40)
